name: Update Credly Badges

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update Badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: shetketu-mitra
          NUMBER_LAST_BADGES: 20
